### ISSUE TITLE
Should qr_read_and_tweet exist?

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_social#13]
If we are releasing software to be useful and understandable for other persons maybe qr_read_and_tweet should be three different packages: 
- One that reads whatever code we want to detect (see #7).
- Another package that does the image branding 
- And the actual tweet module.

These three nodes already exist but they are all compressed in the same package but is not crazy to think that someone may want to use the image branding and by the name of the current package will never be able to know that there is that function, same goes for the code detector. Any opinions on this?

**Comment by cdondrup** [comment]
:+1:

**Comment by Jailander** [comment]
:dart: I guess that is a yes :D so I'll add to my queue :)

**Comment by hawesie** [comment]
:+1:

**Comment by Jailander** [comment]
about qr_read_and_tweet, I think that script was a big hack since it did other things apart from tweeting like stoping the robot and restarting the routine etc, I propose that we create specific nodes that subscribe to the topic published by datamatrix reas for the behaviour that we want the robot to realise for example one only for tweeting, other for starting and pausing etc...
How does that sound @cdondrup?
Meanwhile the current version was removed from the main stream but can be found in https://github.com/Jailander/strands_social/tree/devel

**Comment by cdondrup** [comment]
Sounds good. Will do as soon is someone is using the nhm system again ;)
I think we can close this then. Thanks @Jailander
