### ISSUE TITLE
strands_tweets cannot be released

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_social#22]
hi when trying to catkin_make install the twython submodule cannot be installed because it is not included correctly in setup.py, the problem is that submodule itself has its own setup.py and we don't know how to tackle this

**Comment by marc-hanheide** [comment]
any python wizards who could help with this? @hawesie @cburbridge

**Comment by Jailander** [comment]
@marc-hanheide suggested that he could create a deb package from the pip install of twython this way we would just put it as a dependency that has to be installed

**Comment by Jailander** [comment]
@marc-hanheide tell me as soon as this is done I will remove the submodule from the package

**Comment by marc-hanheide** [comment]
created and released packages using [this procedure](https://gist.github.com/marc-hanheide/0c179ff8d84e38f3ba8d)

`sudo apt-get install python-strands-twython`

You need to create a rosdep key for that in https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/strands.yaml

**Comment by Jailander** [comment]
@marc-hanheide Hi I am trying tu push a release and I am getting this 

```
Could not resolve rosdep key 'strands-twython' for distro 'heisenbug':
No definition of [strands-twython] for OS [fedora]
    rosdep key : strands-twython
    OS name    : fedora
    OS version : heisenbug
    Data: ubuntu:
- python-strands-twython

Try to resolve the problem with rosdep and then continue.
Continue [Y/n]? 
```

I tried the release anyway seemed to work, now is in testing

well waiting to be pulled

**Comment by Jailander** [comment]
It failed giving this error:

```
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/oauthlib-0.7.1.egg-info/top_level.txt'
CMake Error at /opt/ros/hydro/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/tmp/buildd/ros-hydro-strands-tweets-0.0.4-2precise-20141030-1823/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh
  "/usr/bin/python"
  "/opt/ros/hydro/share/catkin/cmake/interrogate_setup_dot_py.py"
  "strands_tweets"
  "/tmp/buildd/ros-hydro-strands-tweets-0.0.4-2precise-20141030-1823/setup.py"
  "/tmp/buildd/ros-hydro-strands-tweets-0.0.4-2precise-20141030-1823/obj-x86_64-linux-gnu/catkin_generated/setup_py_interrogation.cmake")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/hydro/share/catkin/cmake/catkin_python_setup.cmake:69 (safe_execute_process)
  CMakeLists.txt:11 (catkin_python_setup)


-- Configuring incomplete, errors occurred!
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/hydro -DCMAKE_PREFIX_PATH=/opt/ros/hydro returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory `/tmp/buildd/ros-hydro-strands-tweets-0.0.4-2precise-20141030-1823'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
```

do you know what that means? @marc-hanheide

**Comment by marc-hanheide** [comment]
It means that for some reason apparently the file cannot be accessed. Can you check ownership and permission of the files in /usr/local/lib/python2.7/dist-packages/oauthlib-0.7.1.egg-info on your machine and post the result?

**Comment by Jailander** [comment]
```
-rw-r-----  1 root root     1 Oct 30 14:49 dependency_links.txt
-rw-r-----  1 root root  5960 Oct 30 14:49 PKG-INFO
-rw-r-----  1 root root   116 Oct 30 14:49 requires.txt
-rw-r-----  1 root root  4472 Oct 30 14:49 SOURCES.txt
-rw-r-----  1 root root     9 Oct 30 14:49 top_level.txt
```

**Comment by Jailander** [comment]
any clue @marc-hanheide? should I change any  ownership/permission?

**Comment by marc-hanheide** [comment]
finally managed to manually fix the permission in the package... released now
