### ISSUE TITLE
[social_card_reader] Prepare for release

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_social#25]
Please see #24 for the necessary changes.

**Comment by cdondrup** [comment]
Fixed via #26.
Can someone with push rights to the release repo prepare a new release for this, @Jailander @marc-hanheide?

**Comment by marc-hanheide** [comment]
you're an admin now @cdondrup

On 5 November 2014 13:26, Christian Dondrup notifications@github.com
wrote:

> Fixed via #26 https://github.com/strands-project/strands_social/pull/26.
> Can someone with push rights to the release repo prepare a new release for
> this, @Jailander https://github.com/Jailander @marc-hanheide
> https://github.com/marc-hanheide?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strands-project/strands_social/issues/25#issuecomment-61806101
> .

## 

---

Dr. Marc Hanheide
Reader in Computer Science
Room MC3221B
University of Lincoln
Brayford Pool
Lincoln, LN6 7TS
Phone: +44 1522 88 6966
EMail: marc@hanheide.net
Web: http://www.hanheide.net
skype: mah99de
