### ISSUE TITLE
Indigo release

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_social#27]
Needs strands_twython for trusty.

**Comment by marc-hanheide** [comment]
Indeed it does. Is that not available yet?

**Comment by cdondrup** [comment]
Actually I misread the output a bit

```
Could not resolve rosdep key 'strands-twython' for distro 'heisenbug':
No definition of [strands-twython] for OS [fedora]
    rosdep key : strands-twython
    OS name    : fedora
    OS version : heisenbug
    Data: ubuntu:
- python-strands-twython
```

So I could skip the generation for fedora packages?!

**Comment by marc-hanheide** [comment]
yes... I have now disabled fedora in our rosdistro. No idea why I kept that in. Now it shouldn't even try to generate them.

**Comment by cdondrup** [comment]
Has been released
