### ISSUE TITLE
Import twython as submodule

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_social#3]
`strands_tweets` needs [twython](https://github.com/ryanmcgrath/twython). Needs to be imported as a submodule or a rosdep definition before this can be released. Since this is your package @Jailander, could you please take care of that?

**Comment by Jailander** [comment]
I have tested this and works fine I'd say can we close this issue?

**Comment by cdondrup** [comment]
One additional thing, since we are redistributing twython in our package now with this submodule, the License has to include the correct copyright. Can you please make sure that this is reflected properly in our license @Jailander ?

**Comment by Jailander** [comment]
Ok sure didn't think about it let me check and fix if needed

**Comment by Jailander** [comment]
I think now we can close this
