### ISSUE TITLE
Missing dependency for strands_tweets

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_social#30]
```
nah@ubuntu:~$ rosrun strands_tweets tweet.py 
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/strands_tweets/tweet.py", line 7, in <module>
    from twython import Twython, TwythonError
  File "/usr/local/lib/python2.7/dist-packages/twython/__init__.py", line 23, in <module>
    from .api import Twython
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 14, in <module>
    from requests_oauthlib import OAuth1, OAuth2
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth1_auth.py", line 3, in <module>
    from oauthlib.common import extract_params
ImportError: No module named oauthlib.common
```

**Comment by cdondrup** [comment]
We found that as well, that is actually a missing dependency of the the twython package we are hosting.

**Comment by hawesie** [comment]
What's the missing package though? I can't actually find the right thing to make it run.

**Comment by cdondrup** [comment]
We couldn't figure it our ourselves... Only had a few minutes to look at it. maybe @jailander knows

**Comment by Jailander** [comment]
yes I looked into it, apparently the twython oauth dependency was missing in the apt package that we host I will ask @marc-hanheide to take a look at it however meanwhile you can fix it by running `pip install oauthlib`

**Comment by hawesie** [comment]
Thanks guys!

**Comment by marc-hanheide** [comment]
It _should_ be fixed now... I have now idea why that package was empty...

**Comment by marc-hanheide** [comment]
Tested and seems to work on a fresh install... I'll close for now. re-open if the problem persists.

**Comment by marc-hanheide** [comment]
If you see this:
`IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/oauthlib-0.7.2.egg-info/top_level.txt'`
run `sudo chmod 644 /usr/local/lib/python2.7/dist-packages/oauthlib-0.7.2.egg-info/*`

Sorry... the pip installer seems to be somewhat broken here...

**Comment by cdondrup** [comment]
How would that work on the jenkins?

```
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/oauthlib-0.7.2.egg-info/top_level.txt'
CMake Error at /opt/ros/hydro/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/tmp/buildd/ros-hydro-strands-tweets-0.0.8-0precise-20141121-0114/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh
  "/usr/bin/python"
  "/opt/ros/hydro/share/catkin/cmake/interrogate_setup_dot_py.py"
  "strands_tweets"
  "/tmp/buildd/ros-hydro-strands-tweets-0.0.8-0precise-20141121-0114/setup.py"
  "/tmp/buildd/ros-hydro-strands-tweets-0.0.8-0precise-20141121-0114/obj-x86_64-linux-gnu/catkin_generated/setup_py_interrogation.cmake")
  returned error code 1
```

**Comment by cdondrup** [comment]
Currently breaks jenkins regularly. @marc-hanheide can revert that or try to fix it?

**Comment by marc-hanheide** [comment]
On it now!

**Comment by marc-hanheide** [comment]
Fixed by re-releasing with a specific script that fixes permissions after installation:

```
fpm  --iteration 2 -s python -t deb --after-install fixperms.sh --python-package-name-prefix python-strands oauthlib
```

with `fixperms.sh` looking like this:

```
#!/bin/sh
chmod 644 /usr/local/lib/python2.7/dist-packages/oauthlib-0.7.2.egg-info/*
```

**Comment by lucasb-eyer** [comment]
awesome, thanks!
