### ISSUE TITLE
How can we tweet images ?

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/strands_social#6]
Hi,

If it's possible, Can someone please explain how can we tweet images ?

I managed to tweet text from Lucie but I have no idea how to tweet images.

Many thanks,
Muhannad

**Comment by cdondrup** [comment]
@jailander should be able to answer that. Can't remember how it works, really...

**Comment by Jailander** [comment]
Hi, I just noticed that the version that was moved to this repo is not the correct one, the working version is still at https://github.com/Jailander/strands_utils @cdondrup do you have any idea why this could have happened in any case I'll fix it tomorrow morning.

**Comment by cdondrup** [comment]
Wasn't merged before I moved it I reckon.

**Comment by OMARI1988** [comment]
Hi Jaime,

If you can also add how to tweet images I would appreciate it.

Thanks guys,
Muhannad

On Mon, Oct 20, 2014 at 9:01 PM, Christian Dondrup <notifications@github.com

**Comment by Jailander** [comment]
Hi Muhannad,

That is already working but is precisely the part that wasn't moved correctly I'll upload soon with instructions

**Comment by OMARI1988** [comment]
Hi Jaime,

Great! thanks a lot. Can you please let me know once you do.

**Comment by Jailander** [comment]
Ok, done  #8 solves this issue @OMARI1988 you will have to wait until somebody merges it or you can clone my fork https://github.com/Jailander/strands_social into your workspace meanwhile.

**Comment by OMARI1988** [comment]
Great, thanks a lot.

**Comment by Jailander** [comment]
No problem
